# Generated by Django 5.2.11 on 2026-02-19 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '__first__'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('consulta', 'Consulta'), ('vacuna', 'Vacuna'), ('cirugia', 'Cirugía'), ('desparasitacion', 'Desparasitación')], default='consulta', max_length=30)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('medications', models.JSONField(blank=True, default=list)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
            ],
            options={
                'db_table': 'medical_records_record',
                'indexes': [models.Index(fields=['patient', 'created_at'], name='medical_rec_patient_060105_idx'), models.Index(fields=['doctor', 'created_at'], name='medical_rec_doctor__98c9b3_idx'), models.Index(fields=['date'], name='medical_rec_date_47f05d_idx'), models.Index(fields=['type'], name='medical_rec_type_5f474d_idx')],
            },
        ),
    ]
