# Generated by Django 5.2.11 on 2026-02-19 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('consulta', 'Consulta'), ('revision', 'Revisión'), ('vacuna', 'Vacuna'), ('cirugia', 'Cirugía')], default='consulta', max_length=30)),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_show', 'No Show')], default='programada', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reminder', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.owner')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'db_table': 'appointments_appointment',
                'indexes': [models.Index(fields=['doctor', 'date', 'time'], name='appointment_doctor__111942_idx'), models.Index(fields=['patient', 'date'], name='appointment_patient_83aa7a_idx'), models.Index(fields=['owner', 'date'], name='appointment_owner_i_fbd3e0_idx')],
                'unique_together': {('doctor', 'date', 'time')},
            },
        ),
    ]
